"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftBar from "@/layouts/left-bar/LeftBar";
import Header from "@/layouts/header/Header";
import MainContent from "@/layouts/main-content/MainContent";
import { ConfigProvider, App } from "antd";
import useThemeStore from "@/store/useTheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { themeType } = useThemeStore();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={
            themeType === "light-white-black"
              ? {
                  token: {
                    borderRadius: 8,
                  },
                }
              : {
                  token: {
                    borderRadius: 8,
                    colorBorder: "#1e2939",
                    colorText: "white",
                    colorTextPlaceholder: "gray",
                    colorBgContainer: "#000000",
                    colorBgElevated: "#101828 ",
                  },
                }
          }
        >
          <App>
            <div className="h-screen w-screen flex flex-col">
              <Header appName="Note Đi Pls" />
              <div className="flex flex-row w-full h-full">
                <div className="h-full" style={{ width: "400px" }}>
                  <LeftBar />
                </div>
                <div style={{ width: "calc(100% - 400px)" }}>
                  <MainContent>{children}</MainContent>
                </div>
              </div>
            </div>
          </App>
        </ConfigProvider>
      </body>
    </html>
  );
}
